;DEBUG_ENABLE	EQU	1	;デバッグモジュール有効
DEBUG_ENABLE	EQU	0	;デバッグモジュール無効

RAM_SIZE	EQU	8	;8K RAM の場合
;RAM_SIZE	EQU	32	;32K RAM の場合
;RAM_SIZE	EQU	48	;48K RAM の場合

UART	EQU	$8018
;UART	EQU	$afd0
;UART	EQU	$C008
URECV	EQU	UART+1
USEND	EQU	UART+1
USTAT	EQU	UART
UCTRL	EQU	UART

RX_BUFFER_SIZE	EQU	128	;0:受信バッファを使用しない
			;>0:受信バッファを使用する(フロー制御あり)
			;16以上の2^Nの値を指定すること

	IF	RAM_SIZE==32
STACK_TOP	EQU	$8000
SIZE_LIST	EQU	1024*28	;List buffer size
	ELSIF	RAM_SIZE==48
STACK_TOP	EQU	$C000
SIZE_LIST	EQU	1024*44	;List buffer size
	ELSE
STACK_TOP	EQU	$2000
SIZE_LIST	EQU	1024*6	;List buffer size
	ENDIF


KEY_ENTER	EQU	13
KEY_TAB	EQU	9
KEY_BS1	EQU	8
KEY_BS2	EQU	127

BS	EQU	8	;BACKSPACE
CR	EQU	$D	;ENTER KEY
LF	EQU	$A	;ENTER KEY
ESC	EQU	$1B	;ESCAPE CODE
SPACE	EQU	$20	;SPACE (BLANK)


SIZE_LINE	EQU	160	;Command line buffer length + NULL
SIZE_IBUF	EQU	160	;i-code conversion buffer size
SIZE_ARRY	EQU	128	;Array area size
SIZE_NEST_GSTK	EQU	5	;clp(2byte), cip(2byte), lstki(1byte)
NEST_GSTK	EQU	5
SIZE_GSTK	EQU	(SIZE_NEST_GSTK*NEST_GSTK)	;GOSUB stack size(5/nest)
SIZE_NEST_LSTK	EQU	9	;clp(2byte), cip(2byte),to(2byte),step(2byte),var(1byte)
NEST_LSTK	EQU	5
SIZE_LSTK	EQU	(SIZE_NEST_LSTK*NEST_LSTK)	;FOR stack size(9/nest)

ACIA_RESET	EQU	$03
ACIA_DEFAULT	EQU	$15	;clock/16,data 8bit, stop 1bit
	IF	RX_BUFFER_SIZE!=0
ACIA_RTS_HI	EQU	$D5
ACIA_RTS_LO	EQU	$95
	ENDIF

